import Img1 from '../assets/images/furniture-1.png';
import Img2 from '../assets/images/furniture-2.png';
import Img3 from '../assets/images/furniture-3.png';
import Img4 from '../assets/images/furniture-4.png';
import Chair from '../assets/images/chair.png';
import Table from '../assets/images/table.png';
import Bed from '../assets/images/bed.png';
import Closet from '../assets/images/closet.png';

export const allFurnituresData = [
  {
    id: 1,
    img: Img1,
    title: 'Brimnes',
    desc: 'Cabinet with doors, white, 78x95 cm.',
    category: 'drawers',
    price: 100,
  },
  {
    id: 2,
    img: Chair,
    title: 'Chair',
    desc: 'Chair, white.',
    category: 'chairs',
    price: 150,
  },
  {
    id: 3,
    img: Bed,
    title: 'Bed',
    desc: 'Bed, white - gray, 78x95 cm.',
    category: 'beds',
    price: 2000,
  },
  {
    id: 4,
    img: Chair,
    title: 'Chair',
    desc: 'Chair, white.',
    category: 'chairs',
    price: 50,
  },
  {
    id: 5,
    img: Table,
    title: 'Table',
    desc: 'Table, gray.',
    category: 'tables',
    price: 2000,
  },
  {
    id: 6,
    img: Closet,
    title: 'Closet',
    desc: 'Closet with doors, gray.',
    category: 'closets',
    price: 300,
  },
  {
    id: 7,
    img: Table,
    title: 'Table',
    desc: 'Table, white.',
    category: 'tables',
    price: 2000,
  },
  {
    id: 8,
    img: Bed,
    title: 'Bed',
    desc: 'Bed, gray, 2x3 m.',
    category: 'beds',
    price: 700,
  },
  {
    id: 9,
    img: Img2,
    title: 'Brimnes',
    desc: 'Cabinet with doors, white, 78x95 cm.',
    category: 'drawers',
    price: 1400,
  },
  {
    id: 10,
    img: Closet,
    title: 'Closet',
    desc: 'Closet, brown.',
    category: 'closets',
    price: 1090,
  },
  {
    id: 11,
    img: Img3,
    title: 'Brimnes',
    desc: 'Cabinet with doors, white, 78x95 cm.',
    category: 'drawers',
    price: 1000,
  },
  {
    id: 12,
    img: Bed,
    title: 'Bed',
    desc: 'Bed, white, 3x4 m.',
    category: 'beds',
    price: 200,
  },
  {
    id: 13,
    img: Closet,
    title: 'Closet',
    desc: 'Closet, brown, 2x4 m.',
    category: 'closets',
    price: 190,
  },
  {
    id: 14,
    img: Img4,
    title: 'Brimnes',
    desc: 'Cabinet with doors, white, 78x95 cm.',
    category: 'drawers',
    price: 1000,
  },
  {
    id: 15,
    img: Table,
    title: 'Table',
    desc: 'Table, gray.',
    category: 'tables',
    price: 200,
  },
  {
    id: 16,
    img: Chair,
    title: 'Chair',
    desc: 'Chair, white.',
    category: 'chairs',
    price: 50,
  },
];

export const allFurnituresUzData = [
  {
    id: 1,
    img: Img1,
    title: 'Brimnes',
    decc: 'Eshikli shkaf, oq, 78x95 sm.',
    category: 'tortma',
    price: 100,
  },
  {
    id: 2,
    img: Chair,
    title: 'Kreslo',
    desc: 'Kreslo, oq.',
    category: 'stul',
    price: 150,
  },
  {
    id: 3,
    img: Bed,
    title: "to'shak",
    desc: "To'shak, oq - kulrang, 78x95 sm.",
    category: "to'shak",
    price: 2000,
  },
  {
    id: 4,
    img: Chair,
    title: 'Kreslo',
    desc: 'Kreslo, oq.',
    category: 'stul',
    price: 50,
  },
  {
    id: 5,
    img: Table,
    title: 'Table',
    desc: 'Stol, kulrang.',
    category: 'stol',
    price: 2000,
  },
  {
    id: 6,
    img: Closet,
    title: 'Shkaf',
    desc: 'Eshikli shkaf, kulrang.',
    category: 'shkaf',
    price: 300,
  },
  {
    id: 7,
    img: Table,
    title: 'Table',
    desc: 'Stol, oq.',
    category: 'stol',
    price: 2000,
  },
  {
    id: 8,
    img: Bed,
    title: "to'shak",
    desc: "To'shak, kulrang, 2x3 m.",
    category: "to'shak",
    price: 700,
  },
  {
    id: 9,
    img: Img2,
    title: 'Brimnes',
    decc: 'Eshikli shkaf, oq, 78x95 sm.',
    category: 'tortma',
    price: 1400,
  },
  {
    id: 10,
    img: Closet,
    title: 'Shkaf',
    desc: 'Shkaf, jigarrang.',
    category: 'shkaf',
    price: 1090,
  },
  {
    id: 11,
    img: Img3,
    title: 'Brimnes',
    decc: 'Eshikli shkaf, oq, 78x95 sm.',
    category: 'tortma',
    price: 1000,
  },
  {
    id: 12,
    img: Bed,
    title: "to'shak",
    desc: "To'shak, oq, 3x4 m.",
    category: "to'shak",
    price: 200,
  },
  {
    id: 13,
    img: Closet,
    title: 'Shkaf',
    desc: 'Shkaf, jigarrang, 2x4 m.',
    category: 'shkaf',
    price: 190,
  },
  {
    id: 14,
    img: Img4,
    title: 'Brimnes',
    decc: 'Eshikli shkaf, oq, 78x95 sm.',
    category: 'tortma',
    price: 1000,
  },
  {
    id: 15,
    img: Table,
    title: 'Table',
    desc: 'Stol, kulrang.',
    category: 'stol',
    price: 200,
  },
  {
    id: 16,
    img: Chair,
    title: 'Stul',
    desc: 'Stul, oq.',
    category: 'stul',
    price: 50,
  },
];
